# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20171012_1659'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set([('Product_Name', 'user')]),
        ),
    ]
