# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171013_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_ratings',
            field=models.IntegerField(),
        ),
    ]
