# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20171028_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
    ]
