# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20171028_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Cart'),
        ),
    ]
